### ISSUE TITLE
缺少GlideApp这个类。import com.ess.filepicker.model.GlideApp;

### ISSUE THREAD

**Issue by shaohui93** [imLibo/FilePicker#1]
你好，Adapter里面缺少这个类，import com.ess.filepicker.model.GlideApp;

**Comment by imLibo** [comment]
@shaohui93  收到，马上看看

**Comment by imLibo** [comment]
@shaohui93  已解决，你再看看，依赖也更新一哈，更新到'cn.imlibo:FilePicker:v0.0.4_alpha'
