### ISSUE TITLE
选择文件xlsmaxCount=1返回就没有数据list.size=0

### ISSUE THREAD

**Issue by bbbBBBSG** [imLibo/FilePicker#14]
选择文件xlsmaxCount=1返回就没有数据list.size=0
```
FilePicker.from(this)
                        .chooseForBrowser()
                        .setMaxCount(1)
                        .setFileTypes("xls")
                        .requestCode(1)
                        .start();
```
设置为2，选择一个就可以返回

**Comment by 739826946** [comment]
同样的，遇到

**Comment by zr940326** [comment]
在SelectFileByBrowserActivity文件的 onItemClick方法下，找到
 if (SelectOptions.getInstance().isSingle) {}判断，修改为下面，可解决该问题。
` if (SelectOptions.getInstance().isSingle) {
                            Intent result = new Intent();
                            mSelectedFileList.add(item);
                            result.putParcelableArrayListExtra(Const.EXTRA_RESULT_SELECTION, mSelectedFileList);
                            setResult(RESULT_OK, result);
                            super.onBackPressed();
                            return;
                        }`
